### ISSUE TITLE
[question] about license

### ISSUE THREAD

**Issue by ghost** [Nikokrock/ada-lua#5]
My project is licensed under ISC, and I need script support for many of it's features, but I don't want it to be contaminated by GPL.

I see that the repository is licensed under GPLv3 with GCC runtime exception. However, some files have linking exception statements too while others don't (like lua.ads).  
Shouldn't these have a linking exception too, or was this done on purpose?

**Comment by jrmarino** [comment]
To add on to this post (which wasn't responded to 14 months ago), Adacore has been switching out GPLv3 with Apache 2.0 in many cases.

Has then been any thought to following suit?

**Comment by Nikokrock** [comment]
Sorry I missed that question. This was a completely personal project. I confirm that the headers are not all corrects. Will try to fix all of them

**Comment by Nikokrock** [comment]
By the way I will try to change the license to something easier to understand

**Comment by jrmarino** [comment]
awesome, thanks Niko.  Have permissive licenses on bindings especially when the target library is licensed permissively is a welcome thing.

**Comment by Nikokrock** [comment]
I have switched to an MIT License (close to the one used by LUA). Closing the issue.
